// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFduidyaKtw7Ctk0pQf6v4tfRrnxvegwc',
    appId: '1:18324395869:web:aae35aa15b303fa1377ab4',
    messagingSenderId: '18324395869',
    projectId: 'denr-car-e-services-project',
    authDomain: 'denr-car-e-services-project.firebaseapp.com',
    storageBucket: 'denr-car-e-services-project.firebasestorage.app',
    measurementId: 'G-BM8SBE6BMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdtH0w08H6WY9tFM78k85j7HmxbIb4V14',
    appId: '1:18324395869:android:700de6d0a6944882377ab4',
    messagingSenderId: '18324395869',
    projectId: 'denr-car-e-services-project',
    storageBucket: 'denr-car-e-services-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVRUWWJAZUZo2Z9mNsI0ZTRke2xquQVw',
    appId: '1:18324395869:ios:4d7eae88425d13eb377ab4',
    messagingSenderId: '18324395869',
    projectId: 'denr-car-e-services-project',
    storageBucket: 'denr-car-e-services-project.firebasestorage.app',
    iosBundleId: 'com.example.denrCarEServiceApp',
  );
}
